FROM node:14.14-alpine3.12
LABEL maintainer="docker@lagden.in"

ARG PORT=3000
ARG NODE_ENV="development"
ARG PUBLIC_PATH="http://[::1]:3000"
ARG ENDPOINT="http://[::1]:3000"
ARG VERSION="dev"
ARG BASE="/home/node"

ENV PORT=$PORT
ENV NODE_ENV=$NODE_ENV
ENV PUBLIC_PATH=$PUBLIC_PATH
ENV ENDPOINT=$ENDPOINT
ENV VERSION=$VERSION
ENV BASE=$BASE
ENV BASE_APP=$BASE/app

# User
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN deluser --remove-home node
RUN addgroup -S node -g $GROUP_ID
RUN adduser -S -G node -u $USER_ID node

WORKDIR $BASE

ADD --chown=node:node . $BASE_APP

WORKDIR $BASE_APP

RUN npm ci --ignore-scripts

USER node
